"""Pub/Sub-triggered Cloud Function: validate, enrich, and route healthcare claims.

This is the merged entry point for the Claims Validation & Processing Pipeline.
It combines two previously separate ChatGPT-generated builds:

  1. "Serverless Claims Validation Pipeline" — deep structural/coding validation
     (CPT/HCPCS syntax, ICD-10-CM syntax, NPI checksum, medical necessity,
     frequency limits, amount reconciliation).
  2. "Pub/Sub Event-Driven Claims Processing Pipeline" — enrichment (member risk
     score, provider specialty), fraud/quality flagging, and downstream
     streaming aggregation via Dataflow.

Flow:
    Pub/Sub (raw claim) -> validate_and_enrich_claim (this function)
        -> INVALID  -> invalid_claims_topic -> dlq_processor
        -> VALID    -> enrich -> valid_claims_topic -> Dataflow aggregation
                              -> alerts_topic (if fraud flags present)
        -> BigQuery (validated_claims): one audit row per claim, valid or invalid
"""

import json
import logging
from datetime import datetime, timezone
from typing import Any

import functions_framework
from google.cloud import pubsub_v1
from pydantic import ValidationError

from src.bigquery_writer import ClaimsBigQueryWriter, build_validated_claim_row
from src.claim_validator import ClaimsValidator
from src.config import SETTINGS
from src.enrichment import (
    build_idempotency_key,
    calculate_latency_ms,
    detect_fraud_flags,
    detect_quality_flags,
    lookup_member_risk_score,
    lookup_provider_specialty,
    validate_codes_against_references,
)
from src.logging_config import configure_logging
from src.schemas import ClaimRecord
from src.utils import decode_pubsub_message

configure_logging(SETTINGS.log_level)
logger = logging.getLogger(__name__)
publisher = pubsub_v1.PublisherClient()


def _topic_path(topic_name: str) -> str:
    """Build a Pub/Sub topic path for the configured project."""
    return publisher.topic_path(SETTINGS.gcp_project_id, topic_name)


def _publish(topic_name: str, payload: dict[str, Any]) -> str:
    """Publish a JSON payload to Pub/Sub and return the message ID."""
    if not SETTINGS.enable_pubsub_publish:
        return "pubsub-disabled"
    future = publisher.publish(_topic_path(topic_name), json.dumps(payload, default=str).encode("utf-8"))
    return str(future.result())


def _combined_codes(claim: ClaimRecord) -> list[str]:
    """Flatten procedure and diagnosis codes into a single reference-check list."""
    return [p.procedure_code for p in claim.procedures] + [d.icd10_code for d in claim.diagnoses]


@functions_framework.cloud_event
def validate_and_enrich_claim(cloud_event: Any) -> None:
    """
    Validate, enrich, and route one claim from an incoming Pub/Sub CloudEvent.

    Parameters:
        cloud_event: CloudEvent object generated by Pub/Sub.

    Returns:
        None. Results are written to BigQuery and routed to downstream topics.
    """
    received_at = datetime.now(timezone.utc)
    try:
        claim_payload = decode_pubsub_message(cloud_event.data)
        claim = ClaimRecord(**claim_payload)
    except ValidationError as exc:
        payload = {"error_type": "schema_validation_error", "details": exc.errors(), "raw_event": cloud_event.data}
        message_id = _publish(SETTINGS.invalid_claims_topic, payload)
        logger.error("schema_validation_error", extra={"context": {"message_id": message_id, "details": exc.errors()}})
        return
    except Exception as exc:  # pylint: disable=broad-exception-caught
        payload = {
            "error_type": "unexpected_decode_error",
            "details": str(exc),
            "raw_event": getattr(cloud_event, "data", {}),
        }
        message_id = _publish(SETTINGS.invalid_claims_topic, payload)
        logger.exception("unexpected_decode_error", extra={"context": {"message_id": message_id}})
        return

    try:
        result = ClaimsValidator().validate(claim)
        codes = _combined_codes(claim)

        if not result.is_valid:
            row = build_validated_claim_row(
                claim_id=claim.claim_id,
                member_id=claim.member_id,
                provider_npi=claim.provider_npi,
                service_date=claim.date_of_service.isoformat(),
                amount=claim.total_amount,
                codes=codes,
                is_valid=False,
                status=result.status.value,
                errors=result.errors,
                warnings=result.warnings,
                confidence=result.confidence,
                validation_latency_ms=result.validation_latency_ms,
                event_received_at=received_at.isoformat(),
                processed_at=datetime.now(timezone.utc).isoformat(),
                processing_latency_ms=calculate_latency_ms(received_at),
            )
            if SETTINGS.enable_bigquery:
                ClaimsBigQueryWriter().write_claim(row)
            message_id = _publish(SETTINGS.invalid_claims_topic, row)
            logger.info(
                "claim_invalid",
                extra={
                    "context": {
                        "claim_id": claim.claim_id,
                        "status": result.status.value,
                        "message_id": message_id,
                    }
                },
            )
            return

        # Enrichment stage (only runs for claims that pass deep validation)
        member_risk_score = lookup_member_risk_score(claim.member_id, SETTINGS)
        provider_specialty = lookup_provider_specialty(claim.provider_npi, SETTINGS)
        valid_codes, invalid_codes = validate_codes_against_references(codes, SETTINGS)

        enriched: dict[str, Any] = {
            "claim_id": claim.claim_id,
            "member_id": claim.member_id,
            "provider_npi": claim.provider_npi,
            "service_date": claim.date_of_service.isoformat(),
            "amount": claim.total_amount,
            "codes": codes,
            "valid_codes": valid_codes,
            "invalid_codes": invalid_codes,
            "member_risk_score": member_risk_score,
            "provider_specialty": provider_specialty,
        }
        fraud_flags = detect_fraud_flags(enriched, SETTINGS)
        quality_flags = detect_quality_flags(enriched)
        idempotency_key = build_idempotency_key(enriched)
        processed_at = datetime.now(timezone.utc)

        row = build_validated_claim_row(
            claim_id=claim.claim_id,
            member_id=claim.member_id,
            provider_npi=claim.provider_npi,
            service_date=claim.date_of_service.isoformat(),
            amount=claim.total_amount,
            codes=codes,
            is_valid=True,
            status=result.status.value,
            errors=result.errors,
            warnings=result.warnings,
            confidence=result.confidence,
            validation_latency_ms=result.validation_latency_ms,
            valid_codes=valid_codes,
            invalid_codes=invalid_codes,
            member_risk_score=member_risk_score,
            provider_specialty=provider_specialty,
            fraud_flags=fraud_flags,
            quality_flags=quality_flags,
            idempotency_key=idempotency_key,
            event_received_at=received_at.isoformat(),
            processed_at=processed_at.isoformat(),
            processing_latency_ms=calculate_latency_ms(received_at),
        )
        if SETTINGS.enable_bigquery:
            ClaimsBigQueryWriter().write_claim(row)

        message_id = _publish(SETTINGS.valid_claims_topic, row)
        logger.info(
            "claim_valid",
            extra={"context": {"claim_id": claim.claim_id, "status": result.status.value, "message_id": message_id}},
        )

        if fraud_flags:
            alert = {
                "claim_id": claim.claim_id,
                "member_id": claim.member_id,
                "provider_npi": claim.provider_npi,
                "amount": claim.total_amount,
                "fraud_flags": fraud_flags,
                "alert_created_at": datetime.now(timezone.utc).isoformat(),
            }
            _publish(SETTINGS.alerts_topic, alert)

    except Exception as exc:  # pylint: disable=broad-exception-caught
        payload = {
            "error_type": "unexpected_processing_error",
            "details": str(exc),
            "claim_id": getattr(claim, "claim_id", None),
        }
        message_id = _publish(SETTINGS.invalid_claims_topic, payload)
        logger.exception("unexpected_processing_error", extra={"context": {"message_id": message_id}})
